### ISSUE TITLE
Cannot override Girl Avatars from a mod

### ISSUE THREAD

**Issue by CodeZwei** [DPMakerQB/queens-brothel-mod#2]
It seems that you cannot override a girl's avatar from a Mod.

This is because the avatars (i.e. `QueenAvatar.png`) are loaded first as a part of the main menu to display the girls in the save files. Once this is loaded Phaser will treat that asset key as `loaded` and will not reload it.

Currently, there are numerous places in the code where the avatar icon is referenced in code by something like `${girl.id}Avatar` so there is no easy place to change which avatar to use. (For example, change Queen's avatar to use `QueenAvatarRed.png` instead).

See: https://github.com/CodeZwei/red-queen-qbmod for an example.

---

The end result is we can override any asset loaded at game start time, but any asset for the main menu cannot be changed. And simply because the Avatars are loaded at main menu time, they cannot be changed in mods.

---

Possible solutions would be to load a different profile image at Menu time. 

Or add a hook to GirlManager for a function to compute the avatar asset name. `getAvatar: () => return `${this.name}Avatar.png`;` This hook could be modified at play time by a mod to point to a different file. Be sure to update all current locations that reference the avatar to use the hook.

**Comment by DPMakerQB** [comment]
Hi CodeZwei! Thanks for this message. I have actually just removed the avatar image loading from the start of the game. This will take effect in version 0.10.3. I have tested your mod in my dev environment and it is working as intended. Although, your QueenAvatar image needs to be 150x135 for it to work correctly.

You were the first person to call out this broken feature since I updated the main menu, I was hoping I could slip by just long enough until I fixed the code 🤭

Also if you are interested, I am more readily available on Discord to answer any questions you have!
https://discord.gg/hymT8HG

**Comment by CodeZwei** [comment]
Oh haha, well that's a happy coincidence!

I'll wait till 0.10.3 then and try my luck.

--

Would you prefer bug reports and feature requests on discord instead of GitHub? I figured GitHub would be an easier place to track them (at least mod related), but I can do w/e you'd prefer.

**Comment by DPMakerQB** [comment]
Totally up to you. I just respond more quickly over Discord, in case you ever needed me immediately.

**Comment by DPMakerQB** [comment]
Updated the repository to 0.10.3 code! This mod works now.

**Comment by CodeZwei** [comment]
Thanks, just verified myself and it looks like it works 👍
